<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wfwps" nsURI="http://fr.ubo.mde.aitMaksene.wfwps" nsPrefix="wfwps">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DescribedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorflowWps">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wpsLibrary" upperBound="-1"
        eType="#//WPS" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wfLibrary" upperBound="-1"
        eType="#//WorkFlow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WPS" abstract="true" eSuperTypes="#//DescribedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="isCycle singleInputName singleOutputName"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="isCycle" value="WPS.outputs->excludes(Link.output)"/>
      <details key="singleInputName" value="inputs->forAll(i1 : Input, i2 : Input | i1 &lt;> i2 implies i1.identifier &lt;> i2.identifier)"/>
      <details key="singleOutputName" value="outputs->forAll(o1 : Output, o2 : Output | o1 &lt;> o2 implies o1.identifier &lt;> o2.identifier)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" containment="true" eOpposite="#//Input/wps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true" eOpposite="#//Output/wps"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" abstract="true" eSuperTypes="#//DescribedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//WPStype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minOccurs" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxOccurs" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wps" eType="#//WPS" eOpposite="#//WPS/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link" eOpposite="#//Link/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//Data #//InputLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wps" eType="#//WPS" eOpposite="#//WPS/outputs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkFlow" eSuperTypes="#//DescribedElement #//Implementable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wps" ordered="false" unique="false"
        upperBound="-1" eType="#//WPS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedData" upperBound="-1"
        eType="#//ReferencedData" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="sameType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="sameType" value="input.oclIsTypeOf(Output) implies input.oclAsType(Output).type = output.type"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//InputLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Input" eOpposite="#//Input/link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WPStype">
    <eLiterals name="Integer"/>
    <eLiterals name="Float" value="1"/>
    <eLiterals name="String" value="2"/>
    <eLiterals name="Geometry" value="3"/>
    <eLiterals name="Raster" value="4"/>
    <eLiterals name="boolean" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implementable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="default"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalWPS" eSuperTypes="#//WPS #//Implementable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemotelWPS" eSuperTypes="#//WPS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVersion1" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://localhost:8080/geoserver/ows?service=WPS&amp;request=GetCapabilities"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="http://localhost:8080/geoserver/ows"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wpsIdentifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferencedData" eSuperTypes="#//InputLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="http://atlas.gc.ca/cgi-bin/atlaswms_en?VERSION=1.1.1&amp;Request=GetCapabilities&amp;Service=WMS"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isWMS" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="http://atlas.gc.ca/cgi-bin/atlaswms_en"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longueureImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="583"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="largeurImage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="420"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SRS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="EPSG:4326"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bboxX1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-131.13151509433965"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bboxX2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="46.60532747661736"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bboxX3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-117.61620566037737"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bboxX4" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="56.34191403281659"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputLink" abstract="true"/>
</ecore:EPackage>
